name: Fast VPN

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  vpn-node:
    runs-on: ubuntu-latest
    container: archlinux
    steps:
      - name: Включение IP Forwarding (Обязательно для VPN)
        run: |
          pacman -Syu --noconfirm sudo

      - name: Установка Tailscale
        run: curl -fsSL https://tailscale.com/install.sh | sh

      - name: Подключение и создание Exit Node
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          tailscale up --authkey=${TAILSCALE_AUTHKEY} --advertise-exit-node --hostname=github-fast-vpn
          
      - name: Удержание сервера онлайн
        run: |
          echo "VPN запущен! Сервер готов к принятию трафика."
          sleep infinity
